// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;


public enum MoveStyle {
    
    FAST,
    
    SLOW,
    
    IGNORE,
    
    NORMAL,
}

public enum NewEnumNode {
}

public enum ActionStyle {
    
    ATTACK,
    
    ASSAULT,
    
    RAID,
    
    FEINT,
    
    PIN,
    
    YAWP,
    
    SEARCH,
}

public enum SoldierState {
    
    MOVE,
    
    ATTACK,
}

public enum BattleState {
    
    WAITING,
    
    FIGHTING,
    
    CONFUSING,
}
