// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;


public enum MoveStyle {
    
    FAST,
    
    SLOW,
    
    NORMAL,
}

public enum NewEnumNode {
}

public enum ActionStyle {
    
    ATTACK,
    
    ASSAULT,
    
    RAID,
    
    FEINT,
    
    PIN,
    
    YAWP,
    
    SEARCH,
    
    A_ATK,
    
    A_Def,
    
    STANDBY,
}

public enum SoldierState {
    
    MOVE,
    
    ATTACK,
    
    PLAY,
    
    NOTMYTURN,
    
    FINISH,
}

public enum BattleState {
    
    WAITING,
    
    FIGHTING,
    
    CONFUSING,
    
    DEAD,
}

public enum Career {
    
    Swordman,
    
    Archer,
}

public enum SenseStyle {
    
    AGGRESSIVE,
    
    IGNORE,
}

public enum GameState {
    
    Playing,
    
    GameOver,
}
