// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using UniRx;
using uFrame.IOC;
using uFrame.MVVM;
using uFrame.Kernel;


public class SoldierServiceBase : uFrame.Kernel.SystemServiceMonoBehavior {
    
    /// <summary>
    /// This method is invoked whenever the kernel is loading.
    /// Since the kernel lives throughout the entire lifecycle of the game, this will only be invoked once.
    /// </summary>
    public override void Setup() {
        base.Setup();
    }
}

public class GameCalServiceBase : uFrame.Kernel.SystemServiceMonoBehavior {
    
    /// <summary>
    /// This method is invoked whenever the kernel is loading.
    /// Since the kernel lives throughout the entire lifecycle of the game, this will only be invoked once.
    /// </summary>
    public override void Setup() {
        base.Setup();
    }
}
