// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using uFrame.IOC;
using uFrame.Kernel;
using uFrame.MVVM;


public class MainGameSystemLoaderBase : uFrame.Kernel.SystemLoader {
    
    private MainGameRootController _MainGameRootController;
    
    [uFrame.IOC.InjectAttribute()]
    public virtual MainGameRootController MainGameRootController {
        get {
            if (_MainGameRootController==null) {
                _MainGameRootController = Container.CreateInstance(typeof(MainGameRootController)) as MainGameRootController;;
            }
            return _MainGameRootController;
        }
        set {
            _MainGameRootController = value;
        }
    }
    
    public override void Load() {
        Container.RegisterViewModelManager<MainGameRootViewModel>(new ViewModelManager<MainGameRootViewModel>());
        Container.RegisterController<MainGameRootController>(MainGameRootController);
    }
}
