// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using uFrame.IOC;
using uFrame.Kernel;
using uFrame.MVVM;
using uFrame.MVVM.Bindings;
using uFrame.Serialization;
using UnityEngine;
using UniRx;


public partial class UserViewModelBase : uFrame.MVVM.ViewModel {
    
    private P<AuthorizationState> _AuthorizationStateProperty;
    
    private P<WinCondition> _WinConditonProperty;
    
    private ModelCollection<SoldierViewModel> _Soldier;
    
    public UserViewModelBase(uFrame.Kernel.IEventAggregator aggregator) : 
            base(aggregator) {
    }
    
    public virtual P<AuthorizationState> AuthorizationStateProperty {
        get {
            return _AuthorizationStateProperty;
        }
        set {
            _AuthorizationStateProperty = value;
        }
    }
    
    public virtual P<WinCondition> WinConditonProperty {
        get {
            return _WinConditonProperty;
        }
        set {
            _WinConditonProperty = value;
        }
    }
    
    public virtual AuthorizationState AuthorizationState {
        get {
            return AuthorizationStateProperty.Value;
        }
        set {
            AuthorizationStateProperty.Value = value;
        }
    }
    
    public virtual WinCondition WinConditon {
        get {
            return WinConditonProperty.Value;
        }
        set {
            WinConditonProperty.Value = value;
        }
    }
    
    public virtual ModelCollection<SoldierViewModel> Soldier {
        get {
            return _Soldier;
        }
        set {
            _Soldier = value;
        }
    }
    
    public override void Bind() {
        base.Bind();
        _AuthorizationStateProperty = new P<AuthorizationState>(this, "AuthorizationState");
        _WinConditonProperty = new P<WinCondition>(this, "WinConditon");
        _Soldier = new ModelCollection<SoldierViewModel>(this, "Soldier");
    }
    
    public override void Read(ISerializerStream stream) {
        base.Read(stream);
        this.AuthorizationState = (AuthorizationState)stream.DeserializeInt("AuthorizationState");;
        this.WinConditon = (WinCondition)stream.DeserializeInt("WinConditon");;
        if (stream.DeepSerialize) {
            this.Soldier.Clear();
            this.Soldier.AddRange(stream.DeserializeObjectArray<SoldierViewModel>("Soldier"));
        }
    }
    
    public override void Write(ISerializerStream stream) {
        base.Write(stream);
        stream.SerializeInt("AuthorizationState", (int)this.AuthorizationState);;
        stream.SerializeInt("WinConditon", (int)this.WinConditon);;
        if (stream.DeepSerialize) stream.SerializeArray("Soldier", this.Soldier);
    }
    
    protected override void FillCommands(System.Collections.Generic.List<uFrame.MVVM.ViewModelCommandInfo> list) {
        base.FillCommands(list);
    }
    
    protected override void FillProperties(System.Collections.Generic.List<uFrame.MVVM.ViewModelPropertyInfo> list) {
        base.FillProperties(list);
        // PropertiesChildItem
        list.Add(new ViewModelPropertyInfo(_AuthorizationStateProperty, false, false, true, false));
        // PropertiesChildItem
        list.Add(new ViewModelPropertyInfo(_WinConditonProperty, false, false, true, false));
        list.Add(new ViewModelPropertyInfo(_Soldier, true, true, false, false));
    }
}

public partial class UserViewModel {
    
    public UserViewModel(uFrame.Kernel.IEventAggregator aggregator) : 
            base(aggregator) {
    }
}
