using UnityEngine;
using System.Collections;
using System.Collections.Generic;

//Utility script to load head pic sprite to the script for later use.


public class LoadHeadPic : MonoBehaviour
{
	public Dictionary<int,Sprite> imageDict;
	public Dictionary<int,string> nameDict;
	// Use this for initialization

	private string url;

	void Start ()
	{
		url = System.IO.Path.Combine(Application.dataPath, "Resources/Characters/也先帖木兒");

	}
	
	// Update is called once per frame
	void Update ()
	{
	
	}

	public LoadHeadPic(){
	}

	private static readonly LoadHeadPic s_Instance = new LoadHeadPic();
	
	public static LoadHeadPic Instance
	{
		get
		{
			return s_Instance;
		}
	}

	public Sprite YaSinTipMukYi;
	public Sprite YuHim;
	public Sprite NgTseSeui;
	public Sprite BakPei;
	public Sprite SinJan;
	public Sprite SinYing;
	public Sprite LauBakWan;
	public Sprite LauBingChung;
	public Sprite SiNeiGin;
	public Sprite SiSiMing;
	public Sprite SiManShui;
	public Sprite SiMaYi;
	public Sprite NgSaamGwai;
	public Sprite NgHei;
	public Sprite LuiBo;
	public Sprite ChowAhFu;
	public Sprite ChowYu;
	public Sprite ChowSauYing;
	public Sprite JitBit;
	public Sprite SinHongShun;
	public Sprite WongShekGong;
	public Sprite HaHouDun;
	public Sprite GeungTseNga;
	public Sprite SuenMo;
	public Sprite SuenBan;
	public Sprite OnLukShan;
	public Sprite JungJaak;
	public Sprite WaiLiuTse;
	public Sprite WaiChiGingDak;
	public Sprite NgokFei;
	public Sprite SheungYuChun;
	public Sprite LimPaul;
	public Sprite CheungShukYe;
	public Sprite CheungLeung;
	public Sprite CheungLiu;
	public Sprite CheungHop;
	public Sprite CheungFei;
	public Sprite ChuiTat;
	public Sprite NgouLoi;
	public Sprite MoYungYinChiu;
	public Sprite ChikGaiGwong;
	public Sprite SiLong;
	public Sprite ChoGwai;
	public Sprite TsengKwokFan;
	public Sprite ChuBunDeui;
	public Sprite LeeSaiJik;
	public Sprite LeeKwongLee;
	public Sprite LeeManChung;
	public Sprite LeeGingLung;
	public Sprite LeeMuk;
	public Sprite LeeSauNing;
	public Sprite LeeJiShing;
	public Sprite YeungJiCheung;
	public Sprite YeungKwokChung;
	public Sprite YeungYip;
	public Sprite YeungSou;
	public Sprite YeungHou;
	public Sprite LokNgai;
	public Sprite DikChing;
	public Sprite WongBakDong;
	public Sprite WongFaChing;
	public Sprite WongYuenMou;
	public Sprite WongYi;
	public Sprite WongChin;
	public Sprite GumNing;
	public Sprite TinYeungJeui;
	public Sprite ButJoiYu;
	public Sprite PakHei;
	public Sprite ChunLeungYuk;
	public Sprite ChingNgauGam;
	public Sprite MukGwaiYing;
	public Sprite GunChung;
	public Sprite YeLuChucai;
	public Sprite FaMukLan;
	public Sprite MiuFun;
	public Sprite FanTseng;
	public Sprite FanManChing;
	public Sprite FanManFu;
	public Sprite FanYi;
	public Sprite FanYung;
	public Sprite MongTim;
	public Sprite SitYanGwai;
	public Sprite WaiChing;
	public Sprite YuenShungWun;
	public Sprite YuenYingTai;
	public Sprite ChuGotLeung;
	public Sprite HoYeukBut;
	public Sprite ChoiSheungA;
	public Sprite ChiuChe;
	public Sprite ChiuTim;
	public Sprite ChiuWan;
	public Sprite SanYeungSau;
	public Sprite KwokTseYi;
	public Sprite ChengYanTai;
	public Sprite ChengShingGong;
	public Sprite KwanYu;
	public Sprite ChanHingChi;
	public Sprite FokHuiBang;
	public Sprite HonSaiChung;
	public Sprite HongYu;
	public Sprite FeiLim;
	public Sprite MaChiu;
	public Sprite SinYuChungTong;
	public Sprite WongChung;
	public Sprite PongDak;
	public Sprite PongGyun;
	public Sprite PongTung;
	public Sprite CheungSaiKit;

	public static LoadHeadPic SetCharacters(){
		Debug.Log ("LoadHeadPic.SetCharacters()");
		LoadHeadPic headPic = LoadHeadPic.Instance;
		headPic.YaSinTipMukYi  = Instantiate( Resources.Load<Sprite>("Characters/也先帖木兒/Head-YaSinTipMukYi")) as Sprite;
		headPic.YuHim  = Instantiate( Resources.Load<Sprite>("Characters/于謙/YuHim")) as Sprite;
		headPic.NgTseSeui  = Instantiate( Resources.Load<Sprite>("Characters/伍子胥/Head-NgTseSeui")) as Sprite;
		headPic.BakPei  = Instantiate( Resources.Load<Sprite>("Characters/伯嚭/Head-BakPei")) as Sprite;
		headPic.SinJan  = Instantiate( Resources.Load<Sprite>("Characters/先軫/Head-SinJan")) as Sprite;
		headPic.SinYing  = Instantiate( Resources.Load<Sprite>("Characters/冼英/Head-SinYing")) as Sprite;
		headPic.LauBakWan  = Instantiate( Resources.Load<Sprite>("Characters/劉基/Head-LauBakWan")) as Sprite;
		headPic.LauBingChung  = Instantiate( Resources.Load<Sprite>("Characters/劉秉忠/Head-LauBingChung")) as Sprite;
		headPic.SiNeiGin  = Instantiate( Resources.Load<Sprite>("Characters/史彌堅/Head-SiNeiGin")) as Sprite;
		headPic.SiSiMing  = Instantiate( Resources.Load<Sprite>("Characters/史思明/Head-SiSiMing")) as Sprite;
		headPic.SiManShui  = Instantiate( Resources.Load<Sprite>("Characters/史萬歲/SiManShui")) as Sprite;
		headPic.SiMaYi  = Instantiate( Resources.Load<Sprite>("Characters/司馬懿/Head-SiMaYi")) as Sprite;
		headPic.NgSaamGwai  = Instantiate( Resources.Load<Sprite>("Characters/吳三桂/Head-NgSaamGwai")) as Sprite;
		headPic.NgHei  = Instantiate( Resources.Load<Sprite>("Characters/吳起/Head-NgHei")) as Sprite;
		headPic.LuiBo  = Instantiate( Resources.Load<Sprite>("Characters/呂布/Head-LuiBo")) as Sprite;
		headPic.ChowAhFu  = Instantiate( Resources.Load<Sprite>("Characters/周亞夫/Head-ChowAhFu")) as Sprite;
		headPic.ChowYu = Instantiate( Resources.Load<Sprite>("Characters/周瑜/Head-ChowYu")) as Sprite;
		headPic.ChowSauYing  = Instantiate( Resources.Load<Sprite>("Characters/周秀英/Head-ChowSauYing")) as Sprite;
		headPic.JitBit  = Instantiate( Resources.Load<Sprite>("Characters/哲別/Head-JitBit")) as Sprite;
		headPic.SinHongShun  = Instantiate( Resources.Load<Sprite>("Characters/單雄信/SinHongShun")) as Sprite;
		headPic.WongShekGong  = Instantiate( Resources.Load<Sprite>("Characters/圮上老人.黃石公/Head-WongShekGong")) as Sprite;
		headPic.HaHouDun = Instantiate( Resources.Load<Sprite>("Characters/夏侯惇/Head-HaHouDun")) as Sprite;
		headPic.GeungTseNga  = Instantiate( Resources.Load<Sprite>("Characters/姜子牙/Head-GeungTseNga")) as Sprite;
		headPic.SuenMo  = Instantiate( Resources.Load<Sprite>("Characters/孫武/Head-SuenMo")) as Sprite;
		headPic.SuenBan  = Instantiate( Resources.Load<Sprite>("Characters/孫臏/Head-SuenBan")) as Sprite;
		headPic.OnLukShan  = Instantiate( Resources.Load<Sprite>("Characters/安祿山/Head-OnLukShan")) as Sprite;
		headPic.JungJaak = Instantiate( Resources.Load<Sprite>("Characters/宗澤/Head-JungJaak")) as Sprite;
		headPic.WaiLiuTse  = Instantiate( Resources.Load<Sprite>("Characters/尉繚子/Head-WaiLiuTse")) as Sprite;
		headPic.WaiChiGingDak  = Instantiate( Resources.Load<Sprite>("Characters/尉遲敬德/Head-WaiChiGingDak")) as Sprite;
		headPic.NgokFei  = Instantiate( Resources.Load<Sprite>("Characters/岳飛/Head-NgokFei")) as Sprite;
		headPic.SheungYuChun  = Instantiate( Resources.Load<Sprite>("Characters/常遇春/SheungYuChun")) as Sprite;
		headPic.LimPaul = Instantiate( Resources.Load<Sprite>("Characters/廉頗/Head-LimPaul")) as Sprite;
		headPic.CheungShukYe  = Instantiate( Resources.Load<Sprite>("Characters/張叔夜/Head-CheungSukYe")) as Sprite;
		headPic.CheungLeung  = Instantiate( Resources.Load<Sprite>("Characters/張良/Head-CheungLeung")) as Sprite;
		headPic.CheungLiu  = Instantiate( Resources.Load<Sprite>("Characters/張遼/Head-CheungLiu")) as Sprite;
		headPic.CheungHop  = Instantiate( Resources.Load<Sprite>("Characters/張郃/Head-CheungHop")) as Sprite;
		headPic.CheungFei = Instantiate( Resources.Load<Sprite>("Characters/張飛/Head-CheungFei")) as Sprite;
		headPic.ChuiTat  = Instantiate( Resources.Load<Sprite>("Characters/徐達/Head-ChuiTat")) as Sprite;
		headPic.NgouLoi  = Instantiate( Resources.Load<Sprite>("Characters/惡來/Head-NgouLoi")) as Sprite;
		headPic.MoYungYinChiu  = Instantiate( Resources.Load<Sprite>("Characters/慕容延釗/Head-MoYungYinChiu")) as Sprite;
		headPic.ChikGaiGwong  = Instantiate( Resources.Load<Sprite>("Characters/戚繼光/Head-ChikGaiGwong")) as Sprite;
		headPic.SiLong = Instantiate( Resources.Load<Sprite>("Characters/施琅/Head-SiLong")) as Sprite;
		headPic.ChoGwai  = Instantiate( Resources.Load<Sprite>("Characters/曹劌/Head-ChoGwai")) as Sprite;
		headPic.TsengKwokFan  = Instantiate( Resources.Load<Sprite>("Characters/曾國藩/Head-TsengKwokFan")) as Sprite;
		headPic.ChuBunDeui  = Instantiate( Resources.Load<Sprite>("Characters/朱般懟/Head-ChuBunDeui")) as Sprite;
		headPic.LeeSaiJik  = Instantiate( Resources.Load<Sprite>("Characters/李勣/Head-LeeSaiJik")) as Sprite;
		headPic.LeeKwongLee = Instantiate( Resources.Load<Sprite>("Characters/李廣利/Head-LeeKwongLee")) as Sprite;
		headPic.LeeManChung  = Instantiate( Resources.Load<Sprite>("Characters/李文忠/Head-LeeManChung")) as Sprite;
		headPic.LeeGingLung  = Instantiate( Resources.Load<Sprite>("Characters/李景隆/Head-LeeGingLung")) as Sprite;
		headPic.LeeMuk  = Instantiate( Resources.Load<Sprite>("Characters/李牧/Head-LeeMuk")) as Sprite;
		headPic.LeeSauNing  = Instantiate( Resources.Load<Sprite>("Characters/李秀寧/Head-LeeSauNing")) as Sprite;
		headPic.LeeJiShing = Instantiate( Resources.Load<Sprite>("Characters/李自成/Head-LeeJiShing")) as Sprite;
		headPic.YeungJiCheung  = Instantiate( Resources.Load<Sprite>("Characters/楊嗣昌/Head-YeungJiCheung")) as Sprite;
		headPic.YeungKwokChung  = Instantiate( Resources.Load<Sprite>("Characters/楊國忠/Head-YeungKwokChung")) as Sprite;
		headPic.YeungYip  = Instantiate( Resources.Load<Sprite>("Characters/楊業/Head-YeungYip")) as Sprite;
		headPic.YeungSou  = Instantiate( Resources.Load<Sprite>("Characters/楊素/Head-YeungSou")) as Sprite;
		headPic.YeungHou = Instantiate( Resources.Load<Sprite>("Characters/楊鎬/Head-YeungHou")) as Sprite;
		headPic.LokNgai  = Instantiate( Resources.Load<Sprite>("Characters/樂毅/Head-LokNgai")) as Sprite;
		headPic.DikChing  = Instantiate( Resources.Load<Sprite>("Characters/狄青/DikChing")) as Sprite;
		headPic.WongBakDong  = Instantiate( Resources.Load<Sprite>("Characters/王伯當/WongBakDong")) as Sprite;
		headPic.WongFaChing  = Instantiate( Resources.Load<Sprite>("Characters/王化貞/Head-WongFaChing")) as Sprite;
		headPic.WongYuenMou = Instantiate( Resources.Load<Sprite>("Characters/王玄謨/Head-WongYuenMou")) as Sprite;
		headPic.WongYi  = Instantiate( Resources.Load<Sprite>("Characters/王異/Head-WongYi")) as Sprite;
		headPic.WongChin  = Instantiate( Resources.Load<Sprite>("Characters/王翦/Head-WongChin")) as Sprite;
		headPic.GumNing  = Instantiate( Resources.Load<Sprite>("Characters/甘寧/Head-GumNing")) as Sprite;
		headPic.TinYeungJeui  = Instantiate( Resources.Load<Sprite>("Characters/田穰苴/Head-TinYeungJeui")) as Sprite;
		headPic.ButJoiYu = Instantiate( Resources.Load<Sprite>("Characters/畢再遇/Head-ButJoiYu")) as Sprite;
		headPic.PakHei  = Instantiate( Resources.Load<Sprite>("Characters/白起/Head-PakHei")) as Sprite;
		headPic.ChunLeungYuk  = Instantiate( Resources.Load<Sprite>("Characters/秦良玉/Head-ChunLeungYuk")) as Sprite;
		headPic.ChingNgauGam  = Instantiate( Resources.Load<Sprite>("Characters/程咬金/Head-ChingNgauGam")) as Sprite;
		headPic.MukGwaiYing  = Instantiate( Resources.Load<Sprite>("Characters/穆桂英/Head-MukGwaiYing")) as Sprite;
		headPic.GunChung = Instantiate( Resources.Load<Sprite>("Characters/管仲/Head-GunChung")) as Sprite;
		headPic.YeLuChucai  = Instantiate( Resources.Load<Sprite>("Characters/耶律楚材/Head-YeLuChucai")) as Sprite;
		headPic.FaMukLan  = Instantiate( Resources.Load<Sprite>("Characters/花木蘭/Head-FaMukLan")) as Sprite;
		headPic.MiuFun  = Instantiate( Resources.Load<Sprite>("Characters/苗訓/Head-MiuFun")) as Sprite;
		headPic.FanTseng  = Instantiate( Resources.Load<Sprite>("Characters/范增/Head-FanTseng")) as Sprite;
		headPic.FanManChing = Instantiate( Resources.Load<Sprite>("Characters/范文程/Head-FanManChing")) as Sprite;
		headPic.FanManFu  = Instantiate( Resources.Load<Sprite>("Characters/范文虎/Head-FanManFu")) as Sprite;
		headPic.FanYi  = Instantiate( Resources.Load<Sprite>("Characters/范蠡/Head-FanYi")) as Sprite;
		headPic.FanYung  = Instantiate( Resources.Load<Sprite>("Characters/范雍/Head-FanYung")) as Sprite;
		headPic.MongTim  = Instantiate( Resources.Load<Sprite>("Characters/蒙恬/Head-MongTim")) as Sprite;
		headPic.SitYanGwai = Instantiate( Resources.Load<Sprite>("Characters/薛仁貴/Head-SitYanGwai")) as Sprite;
		headPic.WaiChing  = Instantiate( Resources.Load<Sprite>("Characters/衛青/Head-WaiChing")) as Sprite;
		headPic.YuenShungWun  = Instantiate( Resources.Load<Sprite>("Characters/袁崇煥/Head-YuenShungWun")) as Sprite;
		headPic.YuenYingTai  = Instantiate( Resources.Load<Sprite>("Characters/袁應泰/Head-YuenYingTai")) as Sprite;
		headPic.ChuGotLeung  = Instantiate( Resources.Load<Sprite>("Characters/諸葛亮/Head-ChuGotLeung")) as Sprite;
		headPic.HoYeukBut = Instantiate( Resources.Load<Sprite>("Characters/賀若弼/Head-HoYeukBut")) as Sprite;
		headPic.ChoiSheungA  = Instantiate( Resources.Load<Sprite>("Characters/賽尚阿/Head-ChoiSheungA")) as Sprite;
		headPic.ChiuChe  = Instantiate( Resources.Load<Sprite>("Characters/趙奢/Head-ChiuChe")) as Sprite;
		headPic.ChiuTim  = Instantiate( Resources.Load<Sprite>("Characters/趙括/Head-ChiuTim")) as Sprite;
		headPic.ChiuWan  = Instantiate( Resources.Load<Sprite>("Characters/趙雲/Head-ChiuWan")) as Sprite;
		headPic.SanYeungSau = Instantiate( Resources.Load<Sprite>("Characters/辰漾守/Head-SanYeungSau")) as Sprite;
		headPic.KwokTseYi  = Instantiate( Resources.Load<Sprite>("Characters/郭子儀/Head-KwokTseYi")) as Sprite;
		headPic.ChengYanTai  = Instantiate( Resources.Load<Sprite>("Characters/鄭仁泰/Head-ChengYanTai")) as Sprite;
		headPic.ChengShingGong  = Instantiate( Resources.Load<Sprite>("Characters/鄭成功/Head-ChengShingGong")) as Sprite;
		headPic.ChanHingChi  = Instantiate( Resources.Load<Sprite>("Characters/陳慶之/Head-ChanHingChi")) as Sprite;
		headPic.FokHuiBang = Instantiate( Resources.Load<Sprite>("Characters/霍去病/Head-FokHuiBang")) as Sprite;
		headPic.HonSaiChung  = Instantiate( Resources.Load<Sprite>("Characters/韓世忠/Head-HonSaiChung")) as Sprite;
		headPic.HongYu  = Instantiate( Resources.Load<Sprite>("Characters/項羽/Head-HongYu")) as Sprite;
		headPic.FeiLim  = Instantiate( Resources.Load<Sprite>("Characters/飛廉/Head-FeiLim")) as Sprite;
		headPic.MaChiu  = Instantiate( Resources.Load<Sprite>("Characters/馬超/Head-MaChiu")) as Sprite;
		headPic.SinYuChungTong = Instantiate( Resources.Load<Sprite>("Characters/鮮于仲通/Head-SinYuChungTong")) as Sprite;
		headPic.WongChung  = Instantiate( Resources.Load<Sprite>("Characters/黃忠/Head-WongChung")) as Sprite;
		headPic.PongDak  = Instantiate( Resources.Load<Sprite>("Characters/龐德/PongDak")) as Sprite;
		headPic.PongGyun  = Instantiate( Resources.Load<Sprite>("Characters/龐涓/Head-PongGyun")) as Sprite;
		headPic.PongTung  = Instantiate( Resources.Load<Sprite>("Characters/龐統/Head-PongTung")) as Sprite;
		headPic.KwanYu = Instantiate( Resources.Load<Sprite>("Characters/關羽/關公")) as Sprite;
		headPic._setCharacters ();

		return headPic;
	}

	public void _setCharacters(){
		imageDict = new Dictionary<int,Sprite>();
		nameDict = new Dictionary<int,string> ();
		// Add some images.
		imageDict.Add (/*"也先帖木兒",*/1047, YaSinTipMukYi);
		imageDict.Add (/*"于謙",*/25, YuHim);
		imageDict.Add (/*"伍子胥",*/4, NgTseSeui);
		imageDict.Add (/*"伯嚭",*/1074, BakPei);
		imageDict.Add (/*"先軫",*/1068, SinJan);
		imageDict.Add (/*"冼英",*/1059, SinYing);
		imageDict.Add (/*"劉基",*/11, LauBakWan);
		imageDict.Add (/*"劉秉忠",*/14, LauBingChung);
		imageDict.Add (/*"史彌堅",*/1066, SiNeiGin);
		imageDict.Add (/*"史思明",*/1028, SiSiMing);
		imageDict.Add (/*"史萬歲",*/1075, SiManShui);
		imageDict.Add (/*"司馬懿",*/23, SiMaYi);
		imageDict.Add (/*"吳三桂",*/1054, NgSaamGwai);
		imageDict.Add (/*"吳起 ",*/2, NgHei);
		imageDict.Add (/*"呂布",*/1019, LuiBo);
		imageDict.Add (/*"周亞夫",*/1011, ChowAhFu);
		imageDict.Add (/*"周瑜",*/24, ChowYu);
		imageDict.Add (/*"周秀英",*/1056, ChowSauYing);
		imageDict.Add (/*"哲別",*/1035, JitBit);
		imageDict.Add (/*"單雄信",*/1070, SinHongShun);
		imageDict.Add (/*"黃石公",*/18, WongShekGong);
		imageDict.Add (/*"夏侯惇",*/1020, HaHouDun);
		imageDict.Add (/*"姜子牙",*/1, GeungTseNga);
		imageDict.Add (/*"孫武",*/3, SuenMo);
		imageDict.Add (/*"孫臏",*/9, SuenBan);
		imageDict.Add (/*"安祿山",*/1027, OnLukShan);
		imageDict.Add (/*"宗澤",*/1063, JungJaak);
		imageDict.Add (/*"尉繚子",*/19, WaiLiuTse);
		imageDict.Add (/*"尉遲敬德",*/1025, WaiChiGingDak);
		imageDict.Add (/*"岳飛",*/1032, NgokFei);
		imageDict.Add (/*"常遇春",*/1038, SheungYuChun);
		imageDict.Add (/*"廉頗",*/1007, LimPaul);
		imageDict.Add (/*"張叔夜",*/1065, CheungShukYe);
		imageDict.Add (/*"張良",*/10, CheungLeung);
		imageDict.Add (/*"張遼",*/1078, CheungLiu);
		imageDict.Add (/*"張郃",*/1022, CheungHop);
		imageDict.Add (/*"張飛",*/1015, CheungFei);
		imageDict.Add (/*"徐達",*/1036, ChuiTat);
		imageDict.Add (/*"惡來",*/1073, NgouLoi);
		imageDict.Add (/*"慕容延釗",*/1067, MoYungYinChiu);
		imageDict.Add (/*"戚繼光",*/1039, ChikGaiGwong);
		imageDict.Add (/*"施琅",*/1061, SiLong);
		imageDict.Add (/*"曹劌",*/5, ChoGwai);
		imageDict.Add (/*"曾國藩",*/17, TsengKwokFan);
		imageDict.Add (/*"朱般懟",*/28, ChuBunDeui);
		imageDict.Add (/*"李勣",*/1024, LeeSaiJik);
		imageDict.Add (/*"李廣利",*/1042, LeeKwongLee);
		imageDict.Add (/*"李文忠",*/1037, LeeManChung);
		imageDict.Add (/*"李景隆",*/1048, LeeGingLung);
		imageDict.Add (/*"李牧",*/1008, LeeMuk);
		imageDict.Add (/*"李秀寧",*/1058, LeeSauNing);
		imageDict.Add (/*"李自成",*/1055, LeeJiShing);
		imageDict.Add (/*"楊嗣昌",*/1052, YeungJiCheung);
		imageDict.Add (/*"楊國忠",*/26, YeungKwokChung);
		imageDict.Add (/*"楊業",*/1030, YeungYip);
		imageDict.Add (/*"楊素",*/1077, YeungSou);
		imageDict.Add (/*"楊鎬",*/1049, YeungHou);
		imageDict.Add (/*"樂毅",*/1003, LokNgai);
		imageDict.Add (/*"狄青",*/1031, DikChing);
		imageDict.Add (/*"王伯當",*/1069, WongBakDong);
		imageDict.Add (/*"王化貞",*/1050, WongFaChing);
		imageDict.Add (/*"王玄謨",*/1043, WongYuenMou);
		imageDict.Add (/*"王異",*/1060, WongYi);
		imageDict.Add (/*"王翦",*/1009, WongChin);
		imageDict.Add (/*"甘寧",*/1023, GumNing);
		imageDict.Add (/*"田穰苴",*/20, TinYeungJeui);
		imageDict.Add (/*"畢再遇",*/1062, ButJoiYu);
		imageDict.Add (/*"白起",*/1006, PakHei);
		imageDict.Add (/*"秦良玉",*/1057, ChunLeungYuk);
		imageDict.Add (/*"程咬金",*/1071, ChingNgauGam);
		imageDict.Add (/*"穆桂英",*/1033, MukGwaiYing);
		imageDict.Add (/*"管仲",*/6, GunChung);
		imageDict.Add (/*"耶律楚材",*/15, YeLuChucai);
		imageDict.Add (/*"花木蘭",*/1002, FaMukLan);
		imageDict.Add (/*"苗訓",*/13, MiuFun);
		imageDict.Add (/*"范增",*/12, FanTseng);
		imageDict.Add (/*"范文程",*/16, FanManChing);
		imageDict.Add (/*"范文虎",*/1046, FanManFu);
		imageDict.Add (/*"范蠡",*/7, FanYi);
		imageDict.Add (/*"范雍",*/1045, FanYung);
		imageDict.Add (/*"蒙恬",*/1004, MongTim);
		imageDict.Add (/*"薛仁貴",*/1026, SitYanGwai);
		imageDict.Add (/*"衛青",*/1012, WaiChing);
		imageDict.Add (/*"袁崇煥",*/1040, YuenShungWun);
		imageDict.Add (/*"袁應泰",*/1051, YuenYingTai);
		imageDict.Add (/*"諸葛亮",*/8, ChuGotLeung);
		imageDict.Add (/*"賀若弼",*/1076, HoYeukBut);
		imageDict.Add (/*"賽尚阿",*/1053, ChoiSheungA);
		imageDict.Add (/*"趙奢",*/1005, ChiuChe);
		imageDict.Add (/*"趙括",*/27, ChiuTim);
		imageDict.Add (/*"趙雲",*/1016, ChiuWan);
		imageDict.Add (/*"辰漾守",*/29, SanYeungSau);
		imageDict.Add (/*"郭子儀",*/1029, KwokTseYi);
		imageDict.Add (/*"鄭仁泰",*/1064, ChengYanTai);
		imageDict.Add (/*"鄭成功",*/1041, ChengShingGong);
		imageDict.Add (/*"陳慶之",*/1001, ChanHingChi);
		imageDict.Add (/*"霍去病",*/1013, FokHuiBang);
		imageDict.Add (/*"韓世忠",*/1034, HonSaiChung);
		imageDict.Add (/*"項羽",*/1010, HongYu);
		imageDict.Add (/*"飛廉",*/1072, FeiLim);
		imageDict.Add (/*"馬超",*/1017, MaChiu);
		imageDict.Add (/*"鮮于仲通",*/1044, SinYuChungTong);
		imageDict.Add (/*"黃忠",*/1018, WongChung);
		imageDict.Add (/*"龐德",*/1021, PongDak);
		imageDict.Add (/*"龐涓",*/21, PongGyun);
		imageDict.Add (/*"龐統",*/22, PongTung);
		imageDict.Add (/*"關羽",*/1014, KwanYu);
		nameDict.Add (0, "");
		nameDict.Add (1047, "也先帖木兒");
		nameDict.Add (25, "于謙");
		nameDict.Add (4, "伍子胥");
		nameDict.Add (1074, "伯嚭");
		nameDict.Add (1068, "先軫");
		nameDict.Add (1059, "冼英");
		nameDict.Add (11, "劉基");
		nameDict.Add (14, "劉秉忠");
		nameDict.Add (1066, "史彌堅");
		nameDict.Add (1028, "史思明");
		nameDict.Add (1075, "史萬歲");
		nameDict.Add (23, "司馬懿");
		nameDict.Add (1054, "吳三桂");
		nameDict.Add (2, "吳起");
		nameDict.Add (1019, "呂布");
		nameDict.Add (1011, "周亞夫");
		nameDict.Add (24, "周瑜");
		nameDict.Add (1056, "周秀英");
		nameDict.Add (1035, "哲別");
		nameDict.Add (1070, "單雄信");
		nameDict.Add (18, "黃石公");
		nameDict.Add (1020, "夏侯惇");
		nameDict.Add (1, "姜子牙");
		nameDict.Add (3, "孫武");
		nameDict.Add (9, "孫臏");
		nameDict.Add (1027, "安祿山");
		nameDict.Add (1063, "宗澤");
		nameDict.Add (19, "尉繚子");
		nameDict.Add (1025, "尉遲敬德");
		nameDict.Add (1032, "岳飛");
		nameDict.Add (1038, "常遇春");
		nameDict.Add (1007, "廉頗");
		nameDict.Add (1065, "張叔夜");
		nameDict.Add (10, "張良");
		nameDict.Add (1078, "張遼");
		nameDict.Add (1022, "張郃");
		nameDict.Add (1015, "張飛");
		nameDict.Add (1036, "徐達");
		nameDict.Add (1073, "惡來");
		nameDict.Add (1067, "慕容延釗");
		nameDict.Add (1039, "戚繼光");
		nameDict.Add (1061, "施琅");
		nameDict.Add (5, "曹劌");
		nameDict.Add (17, "曾國藩");
		nameDict.Add (28, "朱般懟");
		nameDict.Add (1024, "李勣");
		nameDict.Add (1042, "李廣利");
		nameDict.Add (1037, "李文忠");
		nameDict.Add (1048, "李景隆");
		nameDict.Add (1008, "李牧");
		nameDict.Add (1058, "李秀寧");
		nameDict.Add (1055, "李自成");
		nameDict.Add (1052, "楊嗣昌");
		nameDict.Add (26, "楊國忠");
		nameDict.Add (1030, "楊業");
		nameDict.Add (1077, "楊素");
		nameDict.Add (1049, "楊鎬");
		nameDict.Add (1003, "樂毅");
		nameDict.Add (1031, "狄青");
		nameDict.Add (1069, "王伯當");
		nameDict.Add (1050, "王化貞");
		nameDict.Add (1043, "王玄謨");
		nameDict.Add (1060, "王異");
		nameDict.Add (1009, "王翦");
		nameDict.Add (1023, "甘寧");
		nameDict.Add (20, "田穰苴");
		nameDict.Add (1062, "畢再遇");
		nameDict.Add (1006, "白起");
		nameDict.Add (1057, "秦良玉");
		nameDict.Add (1071, "程咬金");
		nameDict.Add (1033, "穆桂英");
		nameDict.Add (6, "管仲");
		nameDict.Add (15, "耶律楚材");
		nameDict.Add (1002, "花木蘭");
		nameDict.Add (13, "苗訓");
		nameDict.Add (12, "范增");
		nameDict.Add (16, "范文程");
		nameDict.Add (1046, "范文虎");
		nameDict.Add (7, "范蠡");
		nameDict.Add (1045, "范雍");
		nameDict.Add (1004, "蒙恬");
		nameDict.Add (1026, "薛仁貴");
		nameDict.Add (1012, "衛青");
		nameDict.Add (1040, "袁崇煥");
		nameDict.Add (1051, "袁應泰");
		nameDict.Add (8, "諸葛亮");
		nameDict.Add (1076, "賀若弼");
		nameDict.Add (1053, "賽尚阿");
		nameDict.Add (1005, "趙奢");
		nameDict.Add (27, "趙括");
		nameDict.Add (1016, "趙雲");
		nameDict.Add (29, "辰漾守");
		nameDict.Add (1029, "郭子儀");
		nameDict.Add (1064, "鄭仁泰");
		nameDict.Add (1041, "鄭成功");
		nameDict.Add (1001, "陳慶之");
		nameDict.Add (1013, "霍去病");
		nameDict.Add (1034, "韓世忠");
		nameDict.Add (1010, "項羽");
		nameDict.Add (1072, "飛廉");
		nameDict.Add (1017, "馬超");
		nameDict.Add (1044, "鮮于仲通");
		nameDict.Add (1018, "黃忠");
		nameDict.Add (1021, "龐德");
		nameDict.Add (21, "龐涓");
		nameDict.Add (22, "龐統");
		nameDict.Add (1014, "關羽");
	}
}

